version: '3.7'
services:
  webserver:
    container_name: webserver
    image: nginx:latest
    restart: unless-stopped
    ports:
      - '80:80' 
    volumes:
      - type: bind
        source: ./frontend
        target: /var/www/icebear.se
      - type: bind
        source: ./nginx/default.conf
        target: /etc/nginx/conf.d/default.conf  