name: Publish webserver Docker image

on:
  push:
    branches: [ main ]
    paths: 
       - 'src/**'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish-webserver-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.ACCESS_TOKEN }}

    - name: Get the version of pushed tag
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      
    - name: Get the head commit id
      id: get_commit_id
      run: echo ::set-output name=COMMIT_ID::$(echo ${{github.sha}} | head -c 7)
      
    - name: Combine tag and commit id
      id: get_tag_commit_it
      run: echo ::set-output name=TAG_COMMIT_IT::$(echo "${{ steps.get_version.outputs.VERSION }}-${{ steps.get_commit_id.outputs.COMMIT_ID }}")
      
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: v1.0.0 # Optional fallback tag to use when no tag can be found
        
    - uses: jungwinter/split@v2
      id: split
      with:
        msg: ${{ steps.previoustag.outputs.tag }}
        
    - name: test
      run: echo "${{ steps.split.outputs._0 }}"    

      
