name: Test
on:
  push:
    tags:
      - 'v*.*.*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish-webserver-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.ACCESS_TOKEN }}

    - name: Get the version of pushed tag
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      
    - name: Get the head commit id
      id: get_commit_id
      run: echo ::set-output name=COMMIT_ID::$(echo ${{github.sha}} | head -c 7)
      
    - name: Echo
      run: echo "Version; ${{ steps.get_version.outputs.VERSION }}${{ steps.get_commit_id.outputs.COMMIT_ID }}"
