name: Publish webserver Docker image

on:
  push:
    branches: [ main ]
    paths: 
       - 'src/**'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish-webserver-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.ACCESS_TOKEN }}

    - name: Get the version of pushed tag
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      
    - name: Get the head commit id
      id: get_commit_id
      run: echo ::set-output name=COMMIT_ID::$(echo ${{github.sha}} | head -c 7)
      
    - name: Combine tag and commit id
      id: get_tag_commit_it
      run: echo ::set-output name=TAG_COMMIT_IT::$(echo "${{ steps.get_version.outputs.VERSION }}-${{ steps.get_commit_id.outputs.COMMIT_ID }}")
      
    - name: Get previous stable releases
      uses: ankur-lt/get-previous-stable-releases@1.0.2
      id: previousstableversions
      with:
        user: ${{ github.actor }}
        repoName: ${{ github.event.repository.name }}
        accessToken: ${{ secrets.ACCESS_TOKEN }}
      
